// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutkrkzdkpqumcsolsay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dGtya3pka3BxdW1jc29sc2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjkwMzUsImV4cCI6MjA3MTAwNTAzNX0.baBc0j77p11-QR2hL4fWaupvkDsvG1ioyKyBgplg_K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});